baseURL = "/"
languageCode = "en-us"
disableKinds = ["taxonomy"]
enableGitInfo = true

title = "goethe-tcs"

[params]
author = "Holger Dell"
description = "Theoretical Computer Science Group at Goethe University Frankfurt"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
