baseURL = "/"
languageCode = "en-us"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableGitInfo = true

title = "goethe-tcs"

[params]
author = "Holger Dell"
description = "Website of the Theoretical Computer Science Group at Goethe University Frankfurt"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
